{ pkgs, inputs, ... }:
{
  users.users.tom = {
    isNormalUser = true;
    description = "Tom";
    extraGroups = [ "networkmanager" "wheel" "openrazer" "minecraft" ];
    packages = with pkgs; [
      kdePackages.kate
      (inputs.quickshell.packages.${pkgs.stdenv.system}.default.withModules [ kdePackages.qt5compat ])
      vscodium
      lutris
      wineWowPackages.full
      git
      cmake
      libgcc
      gettext
      extra-cmake-modules
      protontricks
      python311
      xorg.xrdb
      linuxHeaders
      openrazer-daemon
      razergenie
      thunderbird
      bottles
      ncdu
      parted
      zoxide
      fzf
      atuin
      btop
      tofi
      youtube-music
      foot
      xorg.xrandr
      xorg.setxkbmap
      brightnessctl
      slurp
      grim
      hyprpicker
      grimblast
      wl-clip-persist
      wl-clipboard
      xclip
      clipnotify
      playerctl
      pamixer
      dialect
      pavucontrol
      pwvucontrol
      socat
      killall
      swappy
      wf-recorder
      mpv
      mpg123
      playerctl
      pinta
      jetbrains.idea
      jetbrains.rider
      dotnet-sdk_8
      dotnet-sdk_9
      mono
      ilspycmd
      glibc
      filezilla
      zip
      steamtinkerlaunch
      wget
      usb-modeswitch
      usbutils
      obs-studio
      video-trimmer
      ffmpeg_7
      streamcontroller
      qpwgraph
      jdk21
      waywall
      (writeShellScriptBin "me3" "/home/tom/.local/bin/me3")
      inputs.putah.packages.${pkgs.stdenv.system}.putah
      jq
      desmume
      unzip
      vesktop
      uwsm
      inputs.prismlauncher.packages.${pkgs.stdenv.system}.prismlauncher
      alvr
      keepassxc
      nodejs_25
      nodePackages."@angular/cli"
      imagemagick
      codebuff
    ];
  };
}
